spring:
  datasource:
    url: jdbc:mysql://47.110.130.104:3306/truism-cms?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456


server:
  port:
    8080

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:site/**/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

truism:
  cms:
    security:
     jwt-key: truism maybe
     expired-in: 6400
